// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3Voiwehn896tiayVjBWXcnkCwtvJejjw',
    appId: '1:1028275901971:web:8c398d581aead9df6711e6',
    messagingSenderId: '1028275901971',
    projectId: 'duckrace-51e68',
    authDomain: 'duckrace-51e68.firebaseapp.com',
    storageBucket: 'duckrace-51e68.firebasestorage.app',
    measurementId: 'G-2G99CWP43B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKQ6Ru6HVEwLDtq0eNTF3RpEEsOt2c_Q4',
    appId: '1:1028275901971:android:93cb4f0ccc4f15886711e6',
    messagingSenderId: '1028275901971',
    projectId: 'duckrace-51e68',
    storageBucket: 'duckrace-51e68.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHna6CP84PU4Lnc2bEm-KTlWUhvrYNmAw',
    appId: '1:1028275901971:ios:f40942f9a968c5566711e6',
    messagingSenderId: '1028275901971',
    projectId: 'duckrace-51e68',
    storageBucket: 'duckrace-51e68.firebasestorage.app',
    iosBundleId: 'com.example.duckrace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHna6CP84PU4Lnc2bEm-KTlWUhvrYNmAw',
    appId: '1:1028275901971:ios:f40942f9a968c5566711e6',
    messagingSenderId: '1028275901971',
    projectId: 'duckrace-51e68',
    storageBucket: 'duckrace-51e68.firebasestorage.app',
    iosBundleId: 'com.example.duckrace',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3Voiwehn896tiayVjBWXcnkCwtvJejjw',
    appId: '1:1028275901971:web:e44b898148922a166711e6',
    messagingSenderId: '1028275901971',
    projectId: 'duckrace-51e68',
    authDomain: 'duckrace-51e68.firebaseapp.com',
    storageBucket: 'duckrace-51e68.firebasestorage.app',
    measurementId: 'G-SLCVJXB158',
  );
}
